### ISSUE TITLE
Error: no UI class available! on CentOS 6.5

### ISSUE THREAD

**Issue by leonsp** [liske/needrestart#18]
Needrestart works ok in bash mode on CentOS 6.5, but dies with an error in regular mode.

```
# cat /etc/*issue*
CentOS release 6.5 (Final)
Kernel \r on an \m

# needrestart
Error: no UI class available!
```

**Comment by alexbarton** [comment]
I'm seeing this as well on CentOS 6.7 …

**Comment by liske** [comment]
Could you please provide the verbose output of `needrestart -v -r l`? What is bash vs. regular mode in CentOS?

**Comment by leonsp** [comment]
Sorry, batch mode, not bash mode. `needrestart -b` works, but it doesn't work without `-b`.

```
# needrestart -v -r l
[main] eval /etc/needrestart/needrestart.conf
[main] running in root-mode
Error loading NeedRestart::UI::stdio: Attempt to reload NeedRestart/UI/stdio.pm aborted.
Compilation failed in require at (eval 18) line 1, <> line 1.
BEGIN failed--compilation aborted at (eval 18) line 1, <> line 1.

Error loading NeedRestart::UI::Debconf: Can't locate parent.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/perl5/vendor_perl/NeedRestart/UI/Debconf.pm line 30, <> line 1.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/NeedRestart/UI/Debconf.pm line 30, <> line 1.
Compilation failed in require at (eval 19) line 1, <> line 1.
BEGIN failed--compilation aborted at (eval 19) line 1, <> line 1.

Error: no UI class available!
```

**Comment by liske** [comment]
It seems that your perl installation is missing parent.pm from the standard run-time libraries. Please try to install the `perl-parent` package which should supply the missing perl package.

**Comment by alexbarton** [comment]
Installing perl-parent (`yum install perl-parent`) fixed it for me, thanks a lot @liske!

**Comment by alexbarton** [comment]
Probably this are all required modules?

```
yum install \
  perl-Module-Find \
  perl-parent \
  perl-Proc-ProcessTable \
  perl-Proc-ProcessTable \
  perl-Sort-Naturally \
  perl-Term-ProgressBar
```

**Comment by leonsp** [comment]
Fixed for me too.

I was installing these via yum:

```
yum -y install \
  gcc \
  git \
  perl-CPAN \
  perl-devel \ 
  perl-ExtUtils-AutoInstall \ 
  perl-ExtUtils-CBuilder \
  perl-ExtUtils-MakeMaker \
  perl-parent
```

And these guys via cpanm:

```
/usr/local/bin/cpanm --force \
  Module::Find \
  Module::ScanDeps \
  Proc::ProcessTable \
  Sort::Naturally \
  Term::ReadKey
```

Looks like I could install all of those via yum, which is nice.
